// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjT4iKvocfrNRxI-CqaL7lBbtzvxNp9fw',
    appId: '1:535543638658:web:e65ee067599c4e9552629b',
    messagingSenderId: '535543638658',
    projectId: 'cpa-flutter-3cb59',
    authDomain: 'cpa-flutter-3cb59.firebaseapp.com',
    storageBucket: 'cpa-flutter-3cb59.appspot.com',
    measurementId: 'G-GB9G1D0G46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgH3w4ysbsOIoWS1vY4KseCffwupku6rY',
    appId: '1:535543638658:android:c30b874ab6c3716c52629b',
    messagingSenderId: '535543638658',
    projectId: 'cpa-flutter-3cb59',
    storageBucket: 'cpa-flutter-3cb59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDSWcP-v0hXrInPqjzvAtzE7k9kJtIJE',
    appId: '1:535543638658:ios:0b32bcd49346970552629b',
    messagingSenderId: '535543638658',
    projectId: 'cpa-flutter-3cb59',
    storageBucket: 'cpa-flutter-3cb59.appspot.com',
    iosBundleId: 'com.example.cpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADDSWcP-v0hXrInPqjzvAtzE7k9kJtIJE',
    appId: '1:535543638658:ios:c4320cb97fd8b49552629b',
    messagingSenderId: '535543638658',
    projectId: 'cpa-flutter-3cb59',
    storageBucket: 'cpa-flutter-3cb59.appspot.com',
    iosBundleId: 'com.example.cpa.RunnerTests',
  );
}
